---
- name: sshd PasswordAuthentication yes
  ansible.builtin.replace:
    path: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication.*$"
    replace: "PasswordAuthentication yes"
- name: restart ssh
  ansible.builtin.systemd:
    name: ssh
    enabled: yes
    daemon_reload: yes
    state: restarted
