---
- name: Nerdfont Installer
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
    owner: "{{ USER }}"
    group: "{{ USER }}"
  with_items:
    - { src: "bin/nerdfonts", dest: "{{ USERBIN }}", mode: "0755" }
- name: Install Nerdfonts
  ansible.builtin.command: "{{ USERBIN }}/nerdfonts {{ item.font }}"
  become_user: "{{ USER }}"
  with_items:
    - { font: "Ubuntu" }
    - { font: "UbuntuMono" }
    - { font: "Hack" }
    - { font: "Noto" }
