---
- name: Converge
  hosts: all
  tasks:
    - name: Update cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      when: ansible_os_family == 'Debian'
    - name: Gitlab-ce
      ansible.builtin.include_role:
        name: gitlab_ce
