---
- name: Node install
  ansible.builtin.import_role:
    name: lang_js

- name: Npmrc
  ansible.builtin.template:
    src: npmrc
    dest: "{{ HOME }}/.npmrc"
    mode: "0644"
    owner: "{{ USER }}"
    group: "{{ USER }}"

- name: Check bash installed
  ansible.builtin.stat:
    path: "/usr/bin/bash"
  register: stat_bash

- name: Cfg 20_js bash
  ansible.builtin.template:
    src: "20_js.cfg"
    dest: "{{ CONFIGDIR }}/bash/20_js.cfg"
    mode: "0644"
    owner: "{{ USER }}"
    group: "{{ USER }}"
  when: stat_bash.stat.exists

- name: Check zsh installed
  ansible.builtin.stat:
    path: "/usr/bin/zsh"
  register: stat_zsh

- name: Cfg 20_js zsh
  ansible.builtin.template:
    src: "20_js.cfg"
    dest: "{{ CONFIGDIR }}/zsh/cfg/20_js.cfg"
    mode: "0644"
    owner: "{{ USER }}"
    group: "{{ USER }}"
  when: stat_zsh.stat.exists
