---
odoo:
  vars:
    home: "/var/lib/odoo"
    config: "/var/lib/odoo/.config"
    local: "/var/lib/odoo/.local"
    user: "odoo"
    odoodir: "/opt/odoo"
    addonsdir: "/opt/addons"
    odooversion: 15.0