---
# install flatpak
- name: install flatpak
  ansible.builtin.apt:
    name:
      - flatpak
    state: present
    update_cache: yes
  when: ansible_os_family == 'Debian'
# install flathub repo
- name: install flathub repo
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: "https://flathub.org/repo/flathub.flatpakrepo"
