---
extends: default

rules:
  line-length:
    max: 200
    level: warning
  indentation:
    spaces: 2
    indent-sequences: consistent
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 1
  comments:
    min-spaces-from-content: 1
  truthy:
    allowed-values:
      - "true"
      - "false"
      - "yes"
      - "no"
    check-keys: false
