#!/bin/sh

GRP=$(pwd | awk -F'/' '{print $NF}')

[ -n "${PLAYBOOK_DIR}" ] || export PLAYBOOK_DIR='./playbooks'

help(){
    printf "install Usage:\n"
    printf "\nOperations:\n"
    printf "\nplay <playbook> <group|guest>\tdeploy ansible playbook onto guest or group"
    printf "\n"
    printf "\nrole <role> <group|guest>\tdeploy ansible role onto guest or group"
    printf "\n"
    printf "\nsyntax <playbook>\t\tcheck the syntax of a playbook"
    printf "\n"
    printf "\nping [all|group|guest]\t\tping the host or group (default all)"
    printf "\n"

}

case "$#" in
    1)
        echo $@
        case "$1" in
            ping) ansible all -m ping -v ;;
            *) help ;;
        esac
        ;;
    2)
        echo $@
        case "$1" in
            ping) ansible ${2} -m ping -v ;;
            syntax)
                ansible-playbook --syntax-check ${PLAYBOOK_DIR}/${2}.yml
                ;;
            *) help ;;
        esac
        ;;
    3)
        echo $@
        case "$1" in
            play)
                [ ${3} = "localhost" ] && export BECOME="-K" || export BECOME=""
                echo ansible-playbook -l ${3} -b ${PLAYBOOK_DIR}/${1}.yml $BECOME
                # ansible-playbook -l ${3} -b ${PLAYBOOK_DIR}/${1}.yml $BECOME
                # [ -n "${1}" ] &&      ansible-playbook -b ${PLAYBOOK_DIR}/${1}.yml $BECOME
                ;;
            role)
                [ ${3} = "localhost" ] && export BECOME="-K" || export BECOME=""
                echo ansible-playbook -l ${3} -e role=${2} -b ${PLAYBOOK_DIR}/apply_role.yml $BECOME
                # ansible-playbook -l ${3} -e role=${2} -b ${PLAYBOOK_DIR}/apply_role.yml $BECOME
                # [ -n "${1}" ] &&      ansible-playbook -e role=${1} -b ${PLAYBOOK_DIR}/apply_role.yml $BECOME
                ;;
            *) help ;;
        esac
        ;;
    *) help ;;
esac
