#!/bin/sh

GRP=$(pwd | awk -F'/' '{print $NF}')

[ -n "${PLAYBOOK_DIR}" ] || export PLAYBOOK_DIR='./ansible_playbooks'

help(){
    printf "install Usage:\n"
    printf "\nOperations:\n"
    printf "\nplay [guest] [playbook]\t\tdeploy ansible playbook onto guest container"
    printf "\nrole [guest] [role]\t\tdeploy ansible role onto guest container"
    printf "\nsetup\t\t\t\tsetup dependencys and download roles/playbooks"
    printf "\n"
}

case "$#" in
    0)
        help
        ;;
    1)
        case "$1" in
            setup)
                pip install -r requirements.txt
                git submodule update --init --recursive --remote
                ;;
            *)
                help
                ;;
        esac
        ;;
    *)
        case "$1" in
            "-h")
                help
                ;;
            play)
                shift
                [ -n "${1}" ] || echo "no guest provided" && [ -n "${2}" ] || echo "no playbook provided" 
                [ ${1} = "localhost" ] && export BECOME="-K" || export BECOME=""
                [ -n "${1}" ] && [ -n "${2}" ] && echo ansible-playbook -l ${1} -b ${PLAYBOOK_DIR}/${2}.yml $BECOME
                [ -n "${1}" ] && [ -n "${2}" ] &&      ansible-playbook -l ${1} -b ${PLAYBOOK_DIR}/${2}.yml $BECOME
                ;;
            role)
                shift
                [ -n "${1}" ] || echo "no guest provided" && [ -n "${2}" ] || echo "no role provided" 
                [ ${1} = "localhost" ] && export BECOME="-K" || export BECOME=""
                [ -n "${1}" ] && [ -n "${2}" ] && echo ansible-playbook -l ${1} -e role=${2} -b ${PLAYBOOK_DIR}/install_role.yml $BECOME
                [ -n "${1}" ] && [ -n "${2}" ] &&      ansible-playbook -l ${1} -e role=${2} -b ${PLAYBOOK_DIR}/install_role.yml $BECOME
                ;;
            *)
                help
                ;;
        esac
        ;;
esac
