#!/bin/sh

GRP=$(pwd | awk -F'/' '{print $NF}')

[ -n "${PLAYBOOK_DIR}" ] || export PLAYBOOK_DIR='./ansible_playbooks'

help(){
    printf "${0} Usage:\n"
    printf "\nOperations:\n"
    printf "\nplay [playbook] [guest]\tdeploy ansible playbook onto target"
    printf "\n"
    printf "\nrole [role] [guest]\tdeploy ansible role onto target"
    printf "\n"
    printf "\nsetup\t\t\tsetup dependencies and download roles/playbooks"
    printf "\n"
}

case "$#" in
    3) 
        case "$1" in
            play)
                shift
                [ ${2} = "localhost" ] && export BECOME="-K" || export BECOME=""
                echo ansible-playbook -l ${2} -b ${PLAYBOOK_DIR}/${1}.yml $BECOME
                ansible-playbook -l ${2} -b ${PLAYBOOK_DIR}/${1}.yml $BECOME
                ;;
            role)
                shift
                [ ${2} = "localhost" ] && export BECOME="-K" || export BECOME=""
                echo ansible-playbook -l ${2} -e role=${1} -b ${PLAYBOOK_DIR}/install_role.yml $BECOME
                ansible-playbook -l ${2} -e role=${1} -b ${PLAYBOOK_DIR}/install_role.yml $BECOME
                ;;
            *)  help ;;
        esac
        ;;
    2) 
        case "$1" in
            play)
                shift
                echo ansible-playbook -b ${PLAYBOOK_DIR}/${1}.yml
                # ansible-playbook -b ${PLAYBOOK_DIR}/${1}.yml
                ;;
            role)
                shift
                echo ansible-playbook -e role=${1} -b ${PLAYBOOK_DIR}/install_role.yml
                # ansible-playbook -e role=${1} -b ${PLAYBOOK_DIR}/install_role.yml
                ;;
            *)  help ;;
        esac
        ;;
    1)
        case "$1" in
            apt)
                sudo apt update
                sudo apt install -y python3-pip python3-venv pipenv direnv git
                echo 'eval "$(direnv hook bash)"' >> $HOME/.bashrc
                git clone https://github.com/ppreeper/ansible_installer
                source $HOME/.bashrc
                ;;
            setup)
                direnv allow
                pipenv install
                git clone https://github.com/ppreeper/ansible_roles
                git clone https://github.com/ppreeper/ansible_playbooks
                ;;
            *)  help ;;
        esac
        ;;
    *)  help ;;
esac
