---
galaxy_info:
  role_name: "lang_ruby"
  namespace: "opensetup"
  author: "ppreeper"
  description: ""
  license: "MIT"
  min_ansible_version: "2.9"
  platforms:
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
  galaxy_tags: []
dependencies: []
