---
- name: Incus
  community.general.snap:
    name: incus
    state: present
  when: ansible_distribution == "Ubuntu"
- name: Add existing user to incus incus-admin "{{ USER }}"
  ansible.builtin.user:
    name: "{{ USER }}"
    groups:
      - incus
      - incus-admin
    append: true
  when: ansible_distribution == "Ubuntu"
