---
- name: Incus
  ansible.builtin.apt:
    name: incus
    state: present
  when: ansible_os_family == 'Debian'
- name: Add existing user to incus incus-admin "{{ USER }}"
  ansible.builtin.user:
    name: "{{ USER }}"
    groups:
      - incus
      - incus-admin
    append: true
  when: ansible_os_family == 'Debian'
