---
# initialize user home
- name: Add mnt dir
  ansible.builtin.file:
    path: "{{ HOME }}/mnt"
    state: directory
    owner: "{{ USER }}"
    group: "{{ USER }}"
    mode: "0775"
- name: Add bin dir
  ansible.builtin.file:
    path: "{{ HOME }}/.local/bin"
    state: directory
    owner: "{{ USER }}"
    group: "{{ USER }}"
    mode: "0775"
- name: Add bash config dir
  ansible.builtin.file:
    path: "{{ CONFIGDIR }}/bash"
    state: directory
    owner: "{{ USER }}"
    group: "{{ USER }}"
    mode: "0775"
- name: Profile add bash config dir
  ansible.builtin.blockinfile:
    path: "{{ HOME }}/.bashrc"
    create: true
    mode: "0644"
    marker: "# {mark} cfg loader"
    block: |
      for f in ${HOME}/.config/bash/*cfg
      do
        source ${f}
      done
- name: Bash-prompt
  ansible.builtin.template:
    src: "bash/00-prompt.cfg"
    dest: "{{ CONFIGDIR }}/bash/00-prompt.cfg"
    mode: "0644"
    owner: "{{ USER }}"
    group: "{{ USER }}"
- name: Bash_autocomplete
  ansible.builtin.template:
    src: "bash/01-bash_autocomplete.cfg"
    dest: "{{ CONFIGDIR }}/bash/01-bash_autocomplete.cfg"
    mode: "0644"
    owner: "{{ USER }}"
    group: "{{ USER }}"
- name: Aliases
  ansible.builtin.template:
    src: "bash/aliases.cfg"
    dest: "{{ CONFIGDIR }}/bash/aliases.cfg"
    mode: "0644"
    owner: "{{ USER }}"
    group: "{{ USER }}"
