---
# initialize user home
- name: add mnt dir
  ansible.builtin.file:
    path: "{{ home }}/mnt"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"

- name: add bin dir
  ansible.builtin.file:
    path: "{{ homebin }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"

- name: add bash config dir
  ansible.builtin.file:
    path: "{{ config }}/bash"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"

- name: profile add bash config dir
  blockinfile:
    path: "{{ home }}/.bashrc"
    create: yes
    marker: "# {mark} cfg loader"
    block: |
      for f in ${HOME}/.config/bash/*cfg
      do
        source ${f}
      done

# bash 00-prompt
- name: 00-prompt
  ansible.builtin.template:
    src: "bash/00-prompt.cfg"
    dest: "{{ config }}/bash/00-prompt.cfg"
    mode: "0644"
    owner: "{{ user }}"
    group: "{{ user }}"

# bash 01-bash_autocomplete
- name: 01-bash_autocomplete
  ansible.builtin.template:
    src: "bash/01-bash_autocomplete.cfg"
    dest: "{{ config }}/bash/01-bash_autocomplete.cfg"
    mode: "0644"
    owner: "{{ user }}"
    group: "{{ user }}"

# bash aliases.cfg
- name: aliases
  ansible.builtin.template:
    src: "bash/aliases.cfg"
    dest: "{{ config }}/bash/aliases.cfg"
    mode: "0644"
    owner: "{{ user }}"
    group: "{{ user }}"
