---
- name: thunderbird uninstall
  ansible.builtin.apt:
    name:
      - thunderbird
    state: absent
  when: ansible_os_family == 'Debian'
- name: evolution groupware client
  ansible.builtin.apt:
    name:
      - evolution
      - evolution-ews
      - evolution-plugin-bogofilter
      - evolution-plugin-pstimport
      - evolution-plugin-spamassassin
      - evolution-plugins
    state: present
  when: ansible_os_family == 'Debian'
