---
- name: sshd PubkeyAuthentication yes
  ansible.builtin.replace:
    path: /etc/ssh/sshd_config
    regexp: "^#PubkeyAuthentication.*$"
    replace: "PubkeyAuthentication yes"
- name: restart ssh
  ansible.builtin.systemd:
    name: ssh
    enabled: yes
    daemon_reload: yes
    state: restarted
