---
- name: Nerdfont Installer
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
    owner: "{{ user }}"
    group: "{{ user }}"
  with_items:
    - { src: "bin/nerdfonts", dest: "{{ homebin }}", mode: "0755" }
- name: Install Nerdfonts
  ansible.builtin.command: "{{ home }}/bin/nerdfonts {{ item.font }}"
  become_user: "{{ user }}"
  with_items:
    - { font: "Ubuntu" }
    - { font: "UbuntuMono" }
    - { font: "Hack" }
    - { font: "Noto" }
