#!/bin/bash
# This script is run after recovery_1st_stage to start Standby node.

set -o xtrace

DEST_NODE_HOST="$1"
DEST_NODE_PGDATA="$2"

PGHOME=/usr/lib/postgresql/{{ POSTGRES_VERSION }}

echo pgpool_remote_start: start: remote start Standby node $DEST_NODE_HOST \
  $(date) >> /var/log/postgresql/exec.log

## Test passwordless SSH
ssh -T -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null postgres@${DEST_NODE_HOST} -i ~/.ssh/{{SSH_KEYID}} ls /tmp > /dev/null

if [ $? -ne 0 ]; then
  echo ERROR: pgpool_remote_start: passwordless SSH to postgres@${DEST_NODE_HOST} failed. Please setup passwordless SSH.
  exit 1
fi

## Start Standby node
ssh -T -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null postgres@$DEST_NODE_HOST -i ~/.ssh/{{SSH_KEYID}} "
  sudo systemctl start postgresql.service
"

if [ $? -ne 0 ]; then
  echo ERROR: pgpool_remote_start: $DEST_NODE_HOST PostgreSQL start failed.
  exit 1
fi

echo pgpool_remote_start: end: PostgreSQL on $DEST_NODE_HOST is started successfully.
exit 0
