---
- name: Git
  ansible.builtin.apt:
    name:
      - git
    state: present
  when: ansible_os_family == 'Debian'
- name: Hugoup
  ansible.builtin.template:
    src: "bin/hugoup"
    dest: "{{ homebin }}/hugoup"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0755"
- name: Install hugo
  ansible.builtin.command: "{{ homebin }}/hugoup"
  become_user: "{{ user }}"
