---
# requirement
- name: Gup
  ansible.builtin.import_role:
    name: gup

# install hugo
- name: Hugo install
  ansible.builtin.command: "/usr/local/bin/gup install hugo"
  become_user: "{{ USER }}"
