---
# dependencies
- name: Install some deps
  ansible.builtin.apt:
    name:
      - direnv
      - nfs-common
      - zip
      - lzop
      - bzip2
      - xz-utils
      - ca-certificates
      - curl
      - dirmngr
      - gnupg
      - locales
      - shared-mime-info
      - libpaper-utils
      - fonts-noto
      - fonts-noto-mono
      - fonts-noto-cjk
      - fonts-liberation
      - gsfonts
      - inetutils-ping
      - libgnutls-dane0
      - libgts-bin
      - python3-babel
      - python3-chardet
      - python3-cryptography
      - python3-cups
      - python3-dateutil
      - python3-decorator
      - python3-docutils
      - python3-feedparser
      - python3-freezegun
      - python3-gevent
      - python3-greenlet
      - python3-html2text
      - python3-idna
      - python3-jinja2
      - python3-libsass
      - python3-ldap
      - python3-lxml
      - python3-markupsafe
      - python3-num2words
      - python3-ofxparse
      - python3-olefile
      - python3-openssl
      - python3-paramiko
      - python3-passlib
      - python3-pil
      - python3-polib
      - python3-pdfminer
      - python3-phonenumbers
      - python3-psutil
      - python3-psycopg2
      - python3-pydot
      - python3-pylibdmtx
      - python3-pyparsing
      - python3-pypdf2
      - python3-serial
      - python3-stdnum
      - python3-pytzdata
      - python3-usb
      - python3-qrcode
      - python3-renderpm
      - python3-reportlab
      - python3-reportlab-accel
      - python3-requests
      - python3-urllib3
      - python3-vobject
      - python3-werkzeug
      - python3-xlrd
      - python3-xlsxwriter
      - python3-xlwt
      - python3-zeep
    state: present
