---
db:
  vars:
    ansible_python_interpreter: "/usr/bin/python3"
    home: "/home/sysadmin"
    config: "/home/sysadmin/.config"
    local: "/home/sysadmin/.local"
    user: "sysadmin"
    distro: "bullseye"
    POSTGRES_VERSION: "14"
    postgresql_major_version: "14"
    POSTGRES_USERNAME: postgres
    POSTGRES_PASSWORD: ArRoToGt00
    POSTGRES_DATADIR: "/db/pgdata"
    postgresql_data_dir_base: "/db/pgdata"    
    POSTGRES_ARCHIVE: "/db/pgarchive"
    POSTGRES_CLUSTER: "main"
    postgresql_cluster_name: "main"
    POSTGRES_PORT: 5433
    postgresql_port: "5432"
    pgbouncer_port: "6432"
    REPL_USERNAME: repl
    patroni_replication_user: "replicator"    
    REPL_PASSWORD: ArReTpGl00
    patroni_replication_pass: "ArReTpGl0i0cator"
    PGPOOL_USERNAME: pgpool
    PGPOOL_PASSWORD: ApRoToHl00
    PGPOOL_PORT: 5432
    PGPOOL_PCP_PORT: 9898
    PGPOOL_WD_PORT: 9000
    PGPOOL_HEARTBEAT_PORT: 9694
    PGPOOL_VIP: 10.0.100.120
    NETIF_COMMON: enp129s0f0
    HOST_NET: 10.0.100.0
    HOST_CIDR: 24
    SSH_KEYID: id_pgpool
    dcs: "etcd"
    dcs_server_ips:
     - 10.0.100.121
     - 10.0.100.122
     - 10.0.100.123
    dcs_port:
      consul:    8500
      zookeeper: 2181
      etcd:      2379
    consul_datacenter: "edm"
    consul_group: "consul"
    patroni_postgres_pass: ""
    patroni_rewind_user: "postgres_rewind"
    patroni_rewind_pass: "ApRoTsGt0g0res_rewind"
    patroni_port: 8008
    vip: "10.0.100.120"