---
proxmox:
  vars:
    ansible_python_interpreter: "/usr/bin/python3"
    home: "/home/sysadmin"
    config: "/home/sysadmin/.config"
    local: "/home/sysadmin/.local"
    user: "sysadmin"
    distro: "bullseye"