#!/bin/bash
CMD="hx"
APP=$(which ${CMD})
REPO="https://github.com/helix-editor/helix"
TAGFILTER="refs/tags"

major=$(git ls-remote --tags ${REPO} | grep ${TAGFILTER} | grep -v -e "{}" -e "stable" -e "nightly" | awk '{print $2}' | sed 's/refs\/tags\///' | awk -F '.' '{print $1}' | sort -g | uniq | tail -1)

minor=$(git ls-remote --tags ${REPO} | grep ${TAGFILTER} | grep -v -e "{}" -e "stable" -e "nightly" | awk '{print $2}' | sed 's/refs\/tags\///' | grep ^$major | awk -F '.' '{print $2}' | sort -g | uniq | tail -1)

patch=$(git ls-remote --tags ${REPO} | grep ${TAGFILTER} | grep -v -e "{}" -e "stable" -e "nightly" | awk '{print $2}' | sed 's/refs\/tags\///' | grep ^$major.$minor| awk -F '.' '{print $3}' | sort -g | uniq | tail -1)

vers=""

if [ "$patch" = "" ]; then
    vers=$major.$minor
else
    vers=$major.$minor.$patch
fi
echo $vers

IDIR=${HOME}/.config/helix
BDIR=/usr/local/bin

function download() {
    echo "download $1 version"
    echo "Installing ${vers}"
    mkdir -p ${IDIR}
    FN=helix-${vers}-x86_64-linux.tar.xz
    rm -f /tmp/${FN}
    wget -qc ${REPO}/releases/download/${vers}/${FN} -O /tmp/${FN}
    tar axf /tmp/${FN} -C ${IDIR} --strip-components=1
    rm -f /tmp/${FN}
}

function uptodate(){
    echo "${CMD} version is current"
}

if [ "${APP}" == "" ]; then
    echo "Not Installed"
    download new
else
    APPVER=$(${APP} -V | grep -e "^helix" | awk '{print $2}')
    APPMAJOR=$(echo $APPVER | awk -F'.' '{print $1}')
    APPMINOR=$(echo $APPVER | awk -F'.' '{print $2}')
    APPPATCH=$(echo $APPVER | awk -F'.' '{print $3}')
    if [ $((${APPMAJOR})) -lt $((${major})) ]; then
        download major
    else
        if [ $((${APPMINOR})) -lt $((${minor})) ]; then
            download minor
        else
            if [ $((${APPPATCH})) -lt $((${patch})) ]; then
                download patch
            else
                uptodate
            fi
        fi
    fi
fi
