---
# GeoIP2 databases downloaded from a third-party mirror (P3TERX/GeoLite.mmdb).
# For production, consider using the official MaxMind geoipupdate tool
# which requires a free license key: https://www.maxmind.com/en/geolite2

- name: GeoIP2 Database Download ASN
  ansible.builtin.get_url:
    url: "https://github.com/P3TERX/GeoLite.mmdb/raw/download/GeoLite2-ASN.mmdb"
    dest: /usr/share/GeoIP/GeoLite2-ASN.mmdb
    mode: "0644"
    force: true
- name: GeoIP2 Database Download City
  ansible.builtin.get_url:
    url: "https://github.com/P3TERX/GeoLite.mmdb/raw/download/GeoLite2-City.mmdb"
    dest: /usr/share/GeoIP/GeoLite2-City.mmdb
    mode: "0644"
    force: true
- name: GeoIP2 Database Download Country
  ansible.builtin.get_url:
    url: "https://github.com/P3TERX/GeoLite.mmdb/raw/download/GeoLite2-Country.mmdb"
    dest: /usr/share/GeoIP/GeoLite2-Country.mmdb
    mode: "0644"
    force: true
