font:
  catalog:
    Noto Serif:
      normal: Noto Serif Regular Nerd Font Complete.ttf
      bold: Noto Serif Bold Nerd Font Complete.ttf
      italic: Noto Serif Italic Nerd Font Complete.ttf
      bold_italic: Noto Serif Bold Italic Nerd Font Complete.ttf
    Noto Sans:
      normal: Noto Sans Regular Nerd Font Complete.ttf
      bold: Noto Sans Display Bold Nerd Font Complete.ttf
      italic: Noto Sans Italic Nerd Font Complete.ttf
      bold_italic: Noto Sans Display Bold Italic Nerd Font Complete.ttf
    Hack:
      normal: Hack Regular Nerd Font Complete.ttf
      bold: Hack Bold Nerd Font Complete.ttf
      italic: Hack Italic Nerd Font Complete.ttf
      bold_italic: Hack Bold Italic Nerd Font Complete.ttf
page:
  background_color: ffffff
  layout: portrait
  initial_zoom: FitH
  margin: [12mm, 17mm, 17mm, 17mm]
  margin_inner: 19mm
  margin_outer: 15mm
  size: Letter
base:
  align: justify
  font_color: 333333
  font_family: Noto Sans
  font_size: 10.5
  line_height_length: round($base_font_size * 1.156)
  line_height: floor($base_line_height_length / $base_font_size)
  font_size_large: round($base_font_size * 1.156)
  font_size_small: round($base_font_size * 0.865)
  font_size_min: round($base_font_size * 0.749)
  font_style: normal
  border_color: eeeeee
  border_radius: 4
  border_width: 0.5
role:
  big:
    font_size: $base_font_size_large
  small:
    font_size: $base_font_size_small
vertical_rhythm: $base_line_height_length
horizontal_rhythm: $base_line_height_length
vertical_spacing: $vertical_rhythm
link:
  font_color: 428bca
literal:
  font_color: b12146
  font_family: Hack
button:
  content: "[\u2009%s\u2009]"
  font_style: bold
key:
  background_color: f5f5f5
  border_color: cccccc
  border_offset: 1.5
  border_radius: 2
  border_width: 0.375
  font_family: $literal_font_family
  separator: "\u202f+\u202f"
mark:
  background_color: ffff00
  border_offset: 0.5
menu:
  caret_content: " <font size=\"1.15em\"><color rgb=\"b12146\">\u203a</color></font> "
heading:
  align: left
  font_color: 3030f0
  font_family: $base_font_family
  font_style: bold
  h1_font_size: floor($base_font_size * 2.6)
  h2_font_size: floor($base_font_size * 2.15)
  h3_font_size: round($base_font_size * 1.7)
  h4_font_size: $base_font_size_large
  h5_font_size: $base_font_size
  h6_font_size: $base_font_size_small
  line_height: 1
  margin_top: $vertical_rhythm * 0.4
  margin_bottom: $vertical_rhythm * 0.9
  min_height_after: $base_line_height_length * 1.5
title_page:
  align: right
  logo:
    top: 10%
  title:
    top: 55%
    font_size: $heading_h1_font_size
    font_color: 999999
    line_height: 0.9
  subtitle:
    font_size: $heading_h3_font_size
    font_style: bold_italic
    line_height: 1
  authors:
    margin_top: $base_font_size * 1.25
    font_size: $base_font_size_large
    font_color: 181818
  revision:
    margin_top: $base_font_size * 1.25
block:
  margin_top: 0
  margin_bottom: $vertical_rhythm
caption:
  align: left
  font_size: $base_font_size * 0.95
  font_style: italic
  margin_inside: $vertical_rhythm / 3
  margin_outside: 0
lead:
  font_size: $base_font_size_large
  line_height: 1.4
abstract:
  font_color: 5c6266
  font_size: $lead_font_size
  line_height: $lead_line_height
  font_style: italic
  first_line_font_style: bold
  title:
    align: center
    font_color: $heading_font_color
    font_family: $heading_font_family
    font_size: $heading_h4_font_size
    font_style: $heading_font_style
admonition:
  column_rule_color: $base_border_color
  column_rule_width: $base_border_width
  padding: [0, $horizontal_rhythm, 0, $horizontal_rhythm]
  label:
    text_transform: uppercase
    font_style: bold
blockquote:
  font_color: $base_font_color
  font_size: $base_font_size_large
  border_color: $base_border_color
  border_width: 5
  padding:
    [
      0,
      $horizontal_rhythm,
      $block_margin_bottom * -0.75,
      $horizontal_rhythm + $blockquote_border_width / 2,
    ]
  cite_font_size: $base_font_size_small
  cite_font_color: 999999
code:
  font_color: $base_font_color
  font_family: $literal_font_family
  font_size: ceil($base_font_size)
  padding: $code_font_size
  line_height: 1.25
  line_gap: 3.8
  background_color: f5f5f5
  border_color: cccccc
  border_radius: $base_border_radius
  border_width: 0.75
conum:
  font_family: $literal_font_family
  font_color: $literal_font_color
  font_size: $base_font_size
  line_height: 4 / 3
  glyphs: circled
example:
  border_color: $base_border_color
  border_radius: $base_border_radius
  border_width: 0.75
  background_color: ffffff
  padding: [$vertical_rhythm, $horizontal_rhythm, 0, $horizontal_rhythm]
image:
  align: left
prose:
  margin_top: $block_margin_top
  margin_bottom: $block_margin_bottom
sidebar:
  background_color: eeeeee
  border_color: e1e1e1
  border_radius: $base_border_radius
  border_width: $base_border_width
  padding:
    [$vertical_rhythm, $vertical_rhythm * 1.25, 0, $vertical_rhythm * 1.25]
  title:
    align: center
    font_color: $heading_font_color
    font_family: $heading_font_family
    font_size: $heading_h4_font_size
    font_style: $heading_font_style
thematic_break:
  border_color: $base_border_color
  border_style: solid
  border_width: $base_border_width
  margin_top: $vertical_rhythm * 0.5
  margin_bottom: $vertical_rhythm * 1.5
description_list:
  term_font_style: bold
  term_spacing: $vertical_rhythm / 4
  description_indent: $horizontal_rhythm * 1.25
outline_list:
  indent: $horizontal_rhythm * 1.5
  item_spacing: $vertical_rhythm / 2
table:
  background_color: $page_background_color
  border_color: dddddd
  border_width: $base_border_width
  cell_padding: 3
  head:
    font_style: bold
    border_bottom_width: $base_border_width * 2.5
  body:
    stripe_background_color: f9f9f9
  foot:
    background_color: f0f0f0
toc:
  indent: $horizontal_rhythm
  line_height: 1.4
  dot_leader:
    font_color: a9a9a9
footnotes:
  font_size: round($base_font_size * 0.75)
  item_spacing: $outline_list_item_spacing / 2
header:
  font_size: $base_font_size_small
  border_color: dddddd
  border_width: 0.25
  height: $base_line_height_length * 2.5
  line_height: 1
  padding: [$base_line_height_length / 2, 1, 0, 1]
  vertical_align: middle
  recto:
    left:
      content: "{docdate}"
    center:
      content: "{document-title}"
  verso:
    left:
      content: $header-recto-left-content
    center:
      content: $header-recto-center-content
footer:
  font_size: $base_font_size_small
  border_color: dddddd
  border_width: 0.25
  height: $base_line_height_length * 2.5
  line_height: 1
  padding: [$base_line_height_length / 2, 1, 0, 1]
  vertical_align: top
  recto:
    right:
      content: "{page-number}"
    center:
      content: "{section-or-chapter-title}"
  verso:
    left:
      content: $footer-recto-right-content
    center:
      content: $footer-recto-center-content
