---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: baseline-debian-12
    image: geerlingguy/docker-debian12-ansible:latest
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
provisioner:
  name: ansible
  config_options:
    defaults:
      vault_password_file: ../../../.vault_pass
verifier:
  name: ansible
