---
- name: Add helix dir
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
  with_items:
    - { path: "{{ config }}/helix" }
- name: Helixup
  ansible.builtin.template:
    src: "helixup"
    dest: "{{ homebin }}/helixup"
    mode: "0750"
    owner: "{{ user }}"
    group: "{{ user }}"
- name: Install nvim
  ansible.builtin.command: "{{ homebin }}/helixup"
  become_user: "{{ user }}"
