---
all:
  vars:
    ansible_python_interpreter: "/usr/bin/python3"
    home: "/home/sysadmin"
    config: "/home/sysadmin/.config"
    local: "/home/sysadmin/.local"
    user: "sysadmin"
    distro: "bullseye"
    DOMAIN: "arthomson.com"
    POSTGRES_VERSION: "14"
    POSTGRES_USERNAME: postgres
    POSTGRES_PASSWORD: ArRoToGt00
    POSTGRES_DATADIR: "/db/pgdata"
    POSTGRES_ARCHIVE: "/db/pgarchive"
    POSTGRES_CLUSTER: "main"
    POSTGRES_PORT: 5433
    REPL_USERNAME: repl
    REPL_PASSWORD: ArReTpGl00
    PGPOOL_USERNAME: pgpool
    PGPOOL_PASSWORD: ApRoToHl00
    PGPOOL_PORT: 5432
    PGPOOL_PCP_PORT: 9898
    PGPOOL_WD_PORT: 9000
    PGPOOL_HEARTBEAT_PORT: 9694
    PGPOOL_VIP: 10.0.100.120
    NETIF_COMMON: enp129s0f0
    HOST_NET: 10.0.100.0
    HOST_CIDR: 24
    SSH_KEYID: id_pgpool
  hosts:
    dba.arthomson.com:
      name: dba
      ip_address: 10.0.100.121
    dbb.arthomson.com:
      name: dbb
      ip_address: 10.0.100.122
    dbc.arthomson.com:
      name: dbc
      ip_address: 10.0.100.123
