---
- import_role:
    name: baseline

# python
- import_role:
    name: python

# postgresql
- import_role:
    name: db_postgresql_repo
- import_role:
    name: db_postgresql_server
- import_role:
    name: db_postgresql_client

# wkhtmltopdf
- import_role:
    name: wkhtmltopdf

# javascript
- import_role:
    name: lang_javascript
- name: rtlcss
  community.general.npm:
    name: rtlcss
    global: yes
    state: present
- name: less
  community.general.npm:
    name: less
    global: yes
    state: present
- name: scss
  community.general.npm:
    name: scss
    global: yes
    state: present

# dependencies
- name: Install some deps
  ansible.builtin.apt:
    name:
      - bzip2
      - file
      - fonts-noto
      - fonts-noto-cjk
      - fonts-noto-mono
      - fonts-liberation
      - gsfonts
      - javascript-common
      - libgnutls-dane0
      - libgts-bin
      - libpaper-utils
      - libssl-dev
      - locales
      - shared-mime-info
      - ssl-cert
      - xdg-user-dirs
      - xz-utils
      - libldap2-dev
      - libxml2-dev
      - libxslt-dev
      - libsasl2-dev
    state: present

# python addons
# - name: install additional python3 addons
# apt:
# name:
# - python3-asn1crypto
# - python3-cffi-backend
# - python3-cryptography
# - python3-docopt
# - python3-html5lib
# - python3-ldap
# - python3-olefile
# - python3-openssl
# - python3-openpyxl
# - python3-phonenumbers
# - python3-psycopg2
# - python3-pygments
# - python3-pyinotify
# - python3-renderpm
# - python3-setuptools
# - python3-watchdog
# state: present

- name: pip addons
  pip:
    executable: pip3
    name:
      - phonenumbers==8.12.11
    state: present
- name: pip odoo base
  pip:
    executable: pip3
    name:
      - Babel==2.6.0
      - chardet==3.0.4
      - decorator==4.3.0
      - docutils==0.14
      - ebaysdk==2.1.5
      - feedparser==5.2.1
      - freezegun==0.3.11
      - html2text==2018.1.9
      - idna==2.6
      - Jinja2==2.10.1
      - libsass==0.17.0
      - Mako==1.0.7
      - MarkupSafe==1.1.0
      - num2words==0.5.6
      - ofxparse==0.19
      - passlib==1.7.1
      - polib==1.1.0
      - psutil==5.6.6
      - pydot==1.4.1
      - pyparsing==2.2.0
      - python-ldap==3.1.0
      - python-stdnum==1.8
      - PyPDF2==1.26.0
      - pyserial==3.4
      - python-dateutil==2.7.3
      - pytz==2019.1
      - pyusb==1.0.2
      - qrcode==6.1
      - reportlab==3.5.13
      - requests==2.21.0
      - vobject==0.9.6.1
      - Werkzeug==0.16.1
      - XlsxWriter==1.1.2
      - xlwt==1.3.*
      - xlrd==1.1.0
      - zeep==3.2.0
    state: present
- name: pip bionic
  pip:
    executable: pip3
    name:
      - gevent==1.1.2
      - greenlet==0.4.10
      - lxml==3.7.1
      - Pillow==5.4.1
        #- psycopg2==2.7.7
      - psycopg2-binary==2.8.6
    state: present
  when: ansible_lsb.codename == "bionic"
- name: pip buster
  pip:
    executable: pip3
    name:
      - gevent==1.5.0
      - greenlet==0.4.15
      - lxml==4.3.2
      - Pillow==6.1.0
        #- psycopg2==2.7.7
      - psycopg2-binary==2.8.6
    state: present
  when: ansible_lsb.codename == "buster"
- name: pip focal
  pip:
    executable: pip3
    name:
      - gevent==1.5.0
      - greenlet==0.4.15
      - lxml==4.3.2
        #- Pillow==6.1.0
        #- psycopg2==2.8.3
      - psycopg2-binary==2.8.6
    state: present
  when: ansible_lsb.codename == "focal"
