---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: apt_mirror_u1804
    image: ubuntu:18.04
  - name: apt_mirror_u2004
    image: ubuntu:20.04
  - name: apt_mirror_u2204
    image: ubuntu:22.04
  - name: apt_mirror_d10
    image: debian:10
  - name: apt_mirror_d11
    image: debian:11
provisioner:
  name: ansible
verifier:
  name: ansible
