---
- name: ruby
  ansible.builtin.apt:
    name:
      - ruby
    state: present
    update_cache: yes
  when: ansible_os_family == 'Debian'
- name: cfg gemrc
  ansible.builtin.template:
    src: "cfg/gemrc"
    dest: "{{ home }}/.gemrc"
    mode: "0640"
    owner: "{{ user }}"
    group: "{{ user }}"


- name: check bash installed
  ansible.builtin.stat:
    path: "/usr/bin/bash"
  register: stat_bash

- name: cfg 20_ruby bash
  ansible.builtin.template:
    src: "20_ruby.cfg"
    dest: "{{ config }}/cfg/20_ruby.cfg"
    mode: "0640"
    owner: "{{ user }}"
    group: "{{ user }}"
  when: stat_bash.stat.exists

- name: check zsh installed
  ansible.builtin.stat:
    path: "/usr/bin/zsh"
  register: stat_zsh

- name: cfg 20_ruby zsh
  ansible.builtin.template:
    src: "20_ruby.cfg"
    dest: "{{ config }}/zsh/cfg/20_ruby.cfg"
    mode: "0640"
    owner: "{{ user }}"
    group: "{{ user }}"
  when: stat_zsh.stat.exists

