---
- name: Oda compile
  become_user: "{{ USER }}"
  ansible.builtin.command: "go install golang.org/preeper/oda@latest"

- name: Install Oda file
  ansible.builtin.copy:
    src: "{{ lookup('pipe', 'go env GOPATH') }}/bin/oda"
    dest: /usr/local/bin/oda
    owner: root
    group: root
    mode: 0755
    backup: no
    force: yes
    validate: oda --version
  when: oda is changed
