---
- name: create {{ rex_user }} group
  ansible.builtin.group:
    name: "{{ rex_user }}"
    state: present
    gid: 1002
- name: create {{ rex_user }} user
  ansible.builtin.user:
    name: "{{ rex_user }}"
    uid: 1002
    groups:
      - "{{ rex_user }}"
      - sudo
    home: "{{ rex_home }}"
    shell: /bin/bash
    state: present
- name: ssh directory
  ansible.builtin.file:
    path: "{{ rex_home }}/.ssh"
    state: directory
    mode: "0700"
    owner: "{{ rex_user }}"
    group: "{{ rex_user }}"
- name: add rex ssh keys
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
    owner: "{{ rex_user }}"
    group: "{{ rex_user }}"
  with_items:
    - { src: "id_rex", dest: "{{ rex_home }}/.ssh/", mode: "0600" }
    - { src: "id_rex.pub", dest: "{{ rex_home }}/.ssh/", mode: "0600" }
- name: rex ssh keys
  ansible.builtin.blockinfile:
    path: /home/rex/.ssh/authorized_keys
    create: true
    mode: 0600
    marker: "# {mark} OERP rex sshkeys"
    block: |
      ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIit6QnmzAiEx+aZv9Q+h5u7NhZWvQs1Cqe4WqOcGlI0 peterp@um35
- name: change ownership
  ansible.builtin.file:
    path: "{{ rex_home }}"
    owner: "{{ rex_user }}"
    group: "{{ rex_user }}"
    recurse: true
