---
all:
  vars:
    ansible_python_interpreter: "/usr/bin/python3"
    home: "/home/cedmuser"
    config: "/home/cedmuser/.config"
    local: "/home/cedmuser/.local"
    user: "root"
    distro: "stretch"
    DOMAIN: "arthomson.com"
  hosts:
    cedm01.arthomson.com:
      name: cedm01
      ip_address: 10.0.100.131
    cedm02.arthomson.com:
      name: cedm02
      ip_address: 10.0.100.132
    cedm03.arthomson.com:
      name: cedm03
      ip_address: 10.0.100.133
    cedm04.arthomson.com:
      name: cedm04
      ip_address: 10.0.100.134
    cedm05.arthomson.com:
      name: cedm05
      ip_address: 10.0.100.135
