---
- name: repository tools
  ansible.builtin.apt:
    name:
      - sudo
      - gnupg2
      - curl
      - wget
      - apt-utils
      - git
      - lsb-release
    state: present
  when: ansible_os_family == 'Debian'
- name: unifi repo key
  ansible.builtin.apt_key:
    url: "https://dl.ui.com/unifi/unifi-repo.gpg"
    state: present
  when: ansible_os_family == 'Debian'
- name: unifi repository stat
  ansible.builtin.stat:
    path: "/etc/apt/sources.list.d/unifi.list"
  register: stat_result
  when: ansible_os_family == 'Debian'
- name: unifi repository add
  ansible.builtin.apt_repository:
    validate_certs: no
    repo: "deb https://www.ui.com/downloads/unifi/debian stable ubiquiti"
    state: present
    filename: unifi
    update_cache: yes
  when: ansible_os_family == 'Debian'
- name: install unifi controller
  ansible.builtin.apt:
    name:
      - unifi
    state: present
  when: ansible_os_family == 'Debian'
