---
- name: Element repo key
  ansible.builtin.apt_key:
    url: "https://packages.riot.im/debian/riot-im-archive-keyring.gpg"
    state: present
  when: ansible_os_family == 'Debian'
- name: Element repository stat
  ansible.builtin.stat:
    path: "/etc/apt/sources.list.d/element.list"
  register: stat_result
  when: ansible_os_family == 'Debian'
- name: Element repository remove
  ansible.builtin.file:
    path: "/etc/apt/sources.list.d/element.list"
    state: absent
  when: stat_result.stat.exists and ansible_os_family == 'Debian'
- name: Element repository add
  ansible.builtin.apt_repository:
    validate_certs: false
    repo: "deb [arch=amd64] https://packages.riot.im/debian/ default main"
    state: present
    filename: element
    update_cache: true
  when: ansible_os_family == 'Debian'
