---
- name: media video tools
  ansible.builtin.apt:
    name:
      - dvdbackup
      - vobcopy
    state: present
  when: ansible_os_family == 'Debian'
- name: media cli helpers
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
    owner: "{{ user }}"
    group: "{{ user }}"
  with_items:
    - { src: "bin/conv.sh", dest: "{{ homebin }}", mode: "0755" }
    - { src: "bin/convwebm", dest: "{{ homebin }}", mode: "0755" }
    - { src: "bin/cpy2mp4", dest: "{{ homebin }}", mode: "0755" }
    - { src: "bin/crop2mp4", dest: "{{ homebin }}", mode: "0755" }
    - { src: "bin/cropdetect", dest: "{{ homebin }}", mode: "0755" }
    - { src: "bin/cropvid2mp4", dest: "{{ homebin }}", mode: "0755" }
    - { src: "bin/cropvob2mp4.sh", dest: "{{ homebin }}", mode: "0755" }
    - { src: "bin/crp2mp4", dest: "{{ homebin }}", mode: "0755" }
    - { src: "bin/drip", dest: "{{ homebin }}", mode: "0755" }
    - { src: "bin/dvd2rip", dest: "{{ homebin }}", mode: "0755" }
    - { src: "bin/dvd2vob", dest: "{{ homebin }}", mode: "0755" }
    - { src: "bin/iso2vob", dest: "{{ homebin }}", mode: "0755" }
    - { src: "bin/mp42mp4", dest: "{{ homebin }}", mode: "0755" }
    - { src: "bin/rip2vob", dest: "{{ homebin }}", mode: "0755" }
    - { src: "bin/v2mp4", dest: "{{ homebin }}", mode: "0755" }
    - { src: "bin/va.sh", dest: "{{ homebin }}", mode: "0755" }
    - { src: "bin/vc.sh", dest: "{{ homebin }}", mode: "0755" }
    - { src: "bin/vhfa.sh", dest: "{{ homebin }}", mode: "0755" }
    - { src: "bin/vhfc.sh", dest: "{{ homebin }}", mode: "0755" }
    - { src: "bin/vhf.sh", dest: "{{ homebin }}", mode: "0755" }
    - { src: "bin/vid2mp4", dest: "{{ homebin }}", mode: "0755" }
    - { src: "bin/vid2srt", dest: "{{ homebin }}", mode: "0755" }
    - { src: "bin/vid2webm", dest: "{{ homebin }}", mode: "0755" }
    - { src: "bin/vidrotate90clock", dest: "{{ homebin }}", mode: "0755" }
    - { src: "bin/vob2mp4", dest: "{{ homebin }}", mode: "0755" }
    - { src: "bin/vpx1pfast", dest: "{{ homebin }}", mode: "0755" }
    - { src: "bin/vr.sh", dest: "{{ homebin }}", mode: "0755" }
