---
patroni:
  hosts:
    dba.preeper.org:
      name: dba.preeper.org
      ip_address: 10.0.30.61
    dbb.preeper.org:
      name: dbb.preeper.org
      ip_address: 10.0.30.62
    dbc.preeper.org:
      name: dbc.preeper.org
      ip_address: 10.0.30.63
  vars:
    ansible_python_interpreter: "/usr/bin/python3"
    home: "/home/sysadmin"
    config: "/home/sysadmin/.config"
    local: "/home/sysadmin/.local"
    user: "sysadmin"
    distro: "jammy"
    DOMAIN: "preeper.org"
    HOST_NET: 10.0.30.0
    HOST_CIDR: 24
    SSH_KEYID: id_pgpool
    vip: "10.0.30.60"
    POSTGRES_VERSION: "15"
    POSTGRES_USERNAME: postgres
    POSTGRES_PASSWORD: ArRoToGt00
    POSTGRES_DATADIR: "/db/pgdata"
    POSTGRES_ARCHIVE: "/db/pgarchive"
    POSTGRES_CLUSTER: "main"
    POSTGRES_PORT: 5433
    pgbouncer_port: "6432"
    PGB_PG_HOST: localhost
    PG_PORT: 5432
    PATRONI_ADMINPASS: "adminpass"
    PATRONI_REPLPASS: "newpass"
    PATRONI_SUPERUSERPASS: "newpass"
    patroni_replication_user: "replicator"
    patroni_replication_pass: "ArReTpGl0i0cator"
    patroni_postgres_pass: ""
    patroni_rewind_user: "postgres_rewind"
    patroni_rewind_pass: "ApRoTsGt0g0res_rewind"
    patroni_port: 8008
    HAPROXY_POSTGRES_PORT: 5000
    HAPROXY_POSTGRES_CLUSTER:
      - dba.preeper.org
      - dbb.preeper.org
      - dbc.preeper.org
    dcs: "etcd"
    dcs_server_ips:
      - 10.0.30.61
      - 10.0.30.62
      - 10.0.30.63
    dcs_port:
      consul: 8500
      zookeeper: 2181
      etcd: 2379
    REPL_USERNAME: repl
    REPL_PASSWORD: ArReTpGl00
