= example cluster

systemctl edit systemd-networkd-wait-online.service

[Service]
ExecStart=
ExecStart=/usr/lib/systemd/systemd-networkd-wait-online --any


mkdir -p /db/pgdata

== deb pkgs

apt install fio git unzip python3-pip haproxy pgbouncer

== consul

consulup

mkdir /etc/consul.d

link:https://devopscube.com/setup-consul-cluster-guide/[]

== patroni

pip3 install patroni[consul] psycopg2-binary

mkdir /etc/patroni

scp examplecluster-dba.yml dba.example.com:/etc/patroni/.
scp examplecluster-dbb.yml dbb.example.com:/etc/patroni/.
scp examplecluster-dbc.yml dbc.example.com:/etc/patroni/.

== postgresql

sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
sudo apt-get update
sudo apt-get -y install postgresql-15

systemctl stop postgresql@15-main.service
systemctl disable postgresql@15-main.service

chmod 0600 /etc/patroni/*yml
chown postgres:postgres /etc/patroni/*yml
chown postgres:postgres /db/pgdata

== status

patronictl -c /etc/patroni/example.yml list example
