---
- name: Set ubuntu code name
  ansible.builtin.set_fact:
    ubuntu_codename: "{{ lookup('ini', 'UBUNTU_CODENAME type=properties file=' + ansible_distribution_file_path) }}"
- name: System details
  ansible.builtin.debug:
    msg: "{{ item }}"
  with_items:
    - "{{ ansible_distribution }}"
    - "{{ ansible_distribution_version }}"
    - "{{ ansible_distribution_major_version }}"
    - "{{ ansible_distribution_release }}"
    - "{{ ubuntu_codename }}"
