---
- name: proxmox-ve
  apt:
    name:
      - proxmox-ve
      - postfix
      - open-iscsi
    state: present
    update_cache: yes
    cache_valid_time: 3600
- name: os-prober
  apt:
    name:
      - os-prober
    state: absent
