---
- name: Minicom config clear
  ansible.builtin.file:
    path: "{{ home }}/.minirc.dfl"
    state: absent
- name: Minicom config
  ansible.builtin.blockinfile:
    path: "{{ home }}/.minirc.dfl"
    mode: "0640"
    group: "{{ user }}"
    create: true
    marker: ""
    block: |
      pu port             /dev/ttyUSB0
      pu baudrate         38400
      pu bits             8
      pu parity           N
      pu stopbits         1
      pu rtscts           No
- name: Minicom config set ownership
  ansible.builtin.file:
    path: "{{ home }}/.minirc.dfl"
    group: "{{ user }}"
    owner: "{{ user }}"
    mode: "0640"
- name: Minicom
  ansible.builtin.apt:
    name:
      - minicom
    state: present
  when: ansible_os_family == 'Debian'
- name: Add existing user to tty,dialout "{{ user }}"
  ansible.builtin.user:
    name: "{{ user }}"
    groups:
      - tty
      - dialout
    append: true
