---
- name: Minicom config
  ansible.builtin.copy:
    dest: "{{ HOME }}/.minirc.dfl"
    content: |
      pu port             /dev/ttyUSB0
      pu baudrate         38400
      pu bits             8
      pu parity           N
      pu stopbits         1
      pu rtscts           No
    mode: "0640"
    owner: "{{ USER }}"
    group: "{{ USER }}"
- name: Minicom
  ansible.builtin.apt:
    name:
      - minicom
    state: present
  when: ansible_os_family == 'Debian'
- name: Add existing user to tty,dialout "{{ USER }}"
  ansible.builtin.user:
    name: "{{ USER }}"
    groups:
      - tty
      - dialout
    append: true
