---
- name: CLI network tools
  ansible.builtin.apt:
    name:
      - nmap
    state: present
    update_cache: true
  when: ansible_os_family == 'Debian'

- name: CLI helpers
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
    owner: "{{ USER }}"
    group: "{{ USER }}"
  with_items:
    - { src: "nscan", dest: "{{ USERBIN }}", mode: "0755" }
