---
- name: Docker snap
  community.general.snap:
    name: docker
    state: present
  when: ansible_distribution == "Ubuntu"
- name: Add existing user to group docker "{{ user }}"
  ansible.builtin.user:
    name: "{{ user }}"
    groups:
      - docker
    append: true
