---
- name: Nextcloud desktop client repo remove
  ansible.builtin.apt_repository:
    validate_certs: false
    repo: "ppa:nextcloud-devs/client"
    state: absent
  when: ansible_distribution == "Ubuntu"
- name: Nextcloud desktop client repo add
  ansible.builtin.apt_repository:
    validate_certs: false
    repo: "ppa:nextcloud-devs/client"
    state: present
  when: ansible_distribution == "Ubuntu"
- name: Nextcloud desktop client
  ansible.builtin.apt:
    name:
      - nextcloud-desktop
    state: present
    update_cache: true
  when: ansible_distribution == "Ubuntu"
