---
- name: Converge
  hosts: all
  tasks:
    - name: update cache
      apt:
        update_cache: true
        cache_valid_time: 3600
      when: ansible_os_family == 'Debian'
    - name: samba_activedirectory
      include_role:
        name: samba_activedirectory
