---
- name: downloaders
  apt:
    name:
      - wget
      - curl
      - aria2
      - netcat
      - pv
    state: present
- name: file utils
  apt:
    name:
      - gddrescue
    state: present
- name: compression
  apt:
    name:
      - lzop
      - pigz
      - cabextract
      - upx-ucl
    state: present
- name: unrar ubuntu
  apt:
    name:
      - unrar
    state: present
  when: ansible_distribution == "Ubuntu"
- name: unrar debian
  apt:
    name:
      - unrar-free
    state: present
  when: ansible_distribution == "Debian"
- name: mail utils
  apt:
    name:
      - swaks
    state: present
- name: monitoring
  apt:
    name:
      - htop
      - nmon
      - tmux
      - screenfetch
    state: present

- name: cli helpers
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
    owner: "{{ user }}"
    group: "{{ user }}"
  with_items:
    - { src: "tordown", dest: "{{ home }}/bin/", mode: "0755" }
