---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: cli_file_utils_u1804
    image: ubuntu:18.04
  - name: cli_file_utils_u2004
    image: ubuntu:20.04
  - name: cli_file_utils_d9
    image: debian:9
  - name: cli_file_utils_d10
    image: debian:10
provisioner:
  name: ansible
verifier:
  name: ansible
