---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: samba_ad_dc_primary_u1804
    image: ubuntu:18.04
  - name: samba_ad_dc_primary_u2004
    image: ubuntu:20.04
  - name: samba_ad_dc_primary_d9
    image: debian:9
  - name: samba_ad_dc_primary_d10
    image: debian:10
provisioner:
  name: ansible
verifier:
  name: ansible
