---
# requirement
- name: git
  ansible.builtin.apt:
    name:
      - git
    state: present
  when: ansible_os_family == 'Debian'

# goup installer
- name: goup installer
  ansible.builtin.template:
    src: "goup"
    dest: "{{ homebin }}/goup"
    mode: "0755"
    owner: "{{ user }}"
    group: "{{ user }}"

# install go
- name: install go
  ansible.builtin.command: "{{ homebin }}/goup"
  become_user: "{{ user }}"

- name: check bash installed
  ansible.builtin.stat:
    path: "/usr/bin/bash"
  register: stat_bash

- name: cfg 20_go bash
  ansible.builtin.template:
    src: "20_go.cfg"
    dest: "{{ config }}/bash/20_go.cfg"
    mode: "0644"
    owner: "{{ user }}"
    group: "{{ user }}"
  when: stat_bash.stat.exists

- name: check zsh installed
  ansible.builtin.stat:
    path: "/usr/bin/zsh"
  register: stat_zsh

- name: cfg 20_go zsh
  ansible.builtin.template:
    src: "20_go.cfg"
    dest: "{{ config }}/zsh/cfg/20_go.cfg"
    mode: "0644"
    owner: "{{ user }}"
    group: "{{ user }}"
  when: stat_zsh.stat.exists
