---
- name: Bun script
  ansible.builtin.uri:
    url: https://bun.sh/install
    return_content: yes
  register: bun_installer
- name: Bun install
  ansible.builtin.shell:
    cmd: bash -s --
    stdin: "{{ bun_installer }}"
