---
- name: mailcatcher pre-reqs
  ansible.builtin.apt:
    name:
      - build-essential
      - ruby
      - ruby-dev
      - libssl-dev
      - libsqlite3-dev
    state: present
    update_cache: yes
  when: ansible_os_family == 'Debian'
- name: mailcatcher
  community.general.gem:
    name: mailcatcher
    state: present
    user_install: no
- name: mailcatcher.service file
  ansible.builtin.template:
    src: "mailcatcher.service"
    dest: "/lib/systemd/system/"
    mode: "0644"
- name: enable mailcatcher.service
  ansible.builtin.systemd:
    name: mailcatcher
    enabled: yes
    daemon_reload: yes
    state: started
