---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: ansible_debug_u1804
    image: ubuntu:18.04
  - name: ansible_debug_u2004
    image: ubuntu:20.04
  - name: ansible_debug_d10
    image: debian:10
provisioner:
  name: ansible
verifier:
  name: ansible
