---
- name: CLI downloaders
  ansible.builtin.apt:
    name:
      - wget
      - curl
      - aria2
      - netcat-openbsd
      - pv
      - rsync
    state: present
- name: CLI file utils
  ansible.builtin.apt:
    name:
      - gddrescue
    state: present
- name: CLI compression
  ansible.builtin.apt:
    name:
      - lzop
      - pigz
      - cabextract
      - upx-ucl
    state: present
- name: CLI unrar ubuntu
  ansible.builtin.apt:
    name:
      - unrar
    state: present
  when: ansible_distribution == "Ubuntu"
- name: CLI unrar debian
  ansible.builtin.apt:
    name:
      - unrar-free
    state: present
  when: ansible_distribution == "Debian"
- name: CLI mail utils
  ansible.builtin.apt:
    name:
      - swaks
    state: present
- name: CLI monitoring
  ansible.builtin.apt:
    name:
      - htop
      - nmon
      - tmux
      - screenfetch
    state: present
- name: CLI network tools
  ansible.builtin.apt:
    name:
      - nmap
    state: present
    update_cache: true
  when: ansible_os_family == 'Debian'
- name: CLI fs utils
  ansible.builtin.apt:
    name:
      - e2fsprogs
      - xfsprogs
      - btrfs-progs
      - ntfs-3g
    update_cache: true
    force: true
    state: present
  when: ansible_os_family == 'Debian'
- name: CLI file utils
  ansible.builtin.apt:
    name:
      - mc
      - fdupes
      - tree
      - rename
      - fzf
      - ripgrep
    state: present
  when: ansible_os_family == 'Debian'
- name: CLI remote file systems
  ansible.builtin.apt:
    name:
      - sshfs
      - nfs-common
    state: present
  when: ansible_os_family == 'Debian'
