---
- name: repository tools
  ansible.builtin.apt:
    name:
      - sudo
      - gnupg2
      - curl
      - wget
      - apt-utils
      - apt-transport-https
      - git
      - lsb-release
    state: present
    update_cache: yes
    cache_valid_time: 3600
  when: ansible_os_family == 'Debian'
