---
- name: AV codec libs
  ansible.builtin.apt:
    name:
      - gstreamer1.0-libav
      - gstreamer1.0-plugins-good
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-plugins-ugly
      - libavcodec-extra
      - ffmpeg
    state: present
  when: ansible_os_family == 'Debian'
