---
proxmox:
  hosts:
    v11.preeper.org:
      name: v11.preeper.org
      ip_address: 10.0.30.11
  vars:
    ansible_python_interpreter: "/usr/bin/python3"
    home: "/home/sysadmin"
    config: "/home/sysadmin/.config"
    local: "/home/sysadmin/.local"
    user: "sysadmin"
    distro: "bookworm"
