---
tsodadev:
  hosts:
    tskent:
      name: tskent
    tspeter:
      name: tspeter
    tsraoul:
      name: tsraoul
    tsdan:
      name: tsdan
    tsbigoa:
      name: tsbigoa
    tsnoah:
      name: tsnoah
  vars:
    domain: odoopro.ca
    node_version: 18
    fs_ip: 10.10.100.204
    logger_ip: 10.10.100.205
    db_ip: 10.10.100.206
