---
- name: Docker.io
  ansible.builtin.apt:
    name:
      - docker.io
    state: present
  when: ansible_os_family == 'Debian'
- name: Add existing user to group docker "{{ user }}"
  ansible.builtin.user:
    name: "{{ user }}"
    groups:
      - docker
    append: true
  when: ansible_os_family == 'Debian'
