#!/bin/bash
mkdir -p "${HOME}/mnt/${1}/${2}/"
sudo mount -t cifs -o credentials=${HOME}/.smbcreds,dir_mode=0777,file_mode=0666,cifsacl,nounix,rsize=8192,wsize=8192 "//${1}/${2}" "${HOME}/mnt/${1}/${2}"
