---
- hosts: all
  name: Desktop-test
  become: true
  roles:
    - nsswitch
    - sysctl_custom
    - baseline
    - userhome
    - cli_utils
    - cli_helpers
    - cli_network
    - cli_filesystems
    - cli_file_utils
    - cli_remote_filesystems
