---
- hosts: all
  become: yes
  roles:
    - kubuntu_ppa_backports
    - update
    - nsswitch
    - baseline
    - sysctl_custom
    - userhome
    - cli_utils
    - cli_helpers
    - cli_network
    - cli_filesystems
    - cli_file_utils
    - cli_remote_filesystems
    - snapd
    - snapd_plasma
    - flatpak
    - flatpak_plasma
    - libreoffice
    - google_chrome
    - nextcloud_client
    - syncthing
    - syncthing_systemd
    - wgvpn
    - remmina
    - virt_viewer
    - teamviewer
    - nvim
    - golang
    - nodejs
    - python
    - kvm
    - docker_io
    - vscode
    - db_sqlite3
    - db_beaver
    - media
    - cadcam
    - asciidoc
    - hugo
    - zoom-client_flatpak
    - update
