---
- hosts: all
  name: Desktop-test
  become: true
  roles:
    - nsswitch
    - sysctl_custom
    - baseline
    - userhome
    - cli/utils
    - cli/helpers
    - cli/network
    - cli/filesystems
    - cli/file_utils
    - cli/remote_filesystems
