---
- hosts: k3s
  name: K3S
  gather_facts: true
  become: true
  roles:
    - role: k3s/prereq
    - role: k3s/download
    - role: k3s/raspberrypi

- hosts: master
  become: true
  roles:
    - role: k3s/master

- hosts: falsede
  become: true
  roles:
    - role: k3s/node
