---
- hosts: mail
  name: Mailserver
  roles:
    - apt_mirror
    - update
    - baseline
    - snapd
    - sqlite3
    - certbot
    - vmail_user
    - postfix
    - postfix_config
    - dovecot/install
    - dovecot/config
    - clamav
    - rspamd
    - fail2ban
