---
- hosts: odoo
  name: Odoo Node
  roles:
    - apt_mirror
    - update
    - hosts_file
    - sysctl_custom
    - baseline
    - nfs_common
    - lang/python
    - lang/nodejs
    - db/postgresql_client
    - wkhtmltopdf
    - odoo/base
    - odoo/log
    - odoo/fstab
    - odoo/service
    - odoo/service_enable
    - update
    - reboot
