---
- hosts: odoo
  name: Odoo Prd
  roles:
    - odoo/base
    - odoo/user_chsh
    - odoo/config
    - odoo/db
    - userhome
    - lang/python
    - lang/nodejs
    - neovim/dev
  tasks:
    - name: Update odoo user
      user:
        name: "odoo"
        ansible.builtin.shell: "/bin/bash"
        groups: odoo,sudo
