---
- hosts: odoo
  name: Odoo Prd
  roles:
    - odoo_base
    - odoo_user_chsh
    - odoo_config
    - odoo_db
    - userhome
    - lang_python
    - lang_nodejs
    - neovim_dev
  tasks:
    - name: Update odoo user
      user:
        name: "odoo"
        ansible.builtin.shell: "/bin/bash"
        groups: odoo,sudo
