---
- hosts: samba
  name: Samba Primary DC
  roles:
    - update
    - cli_utils
    - hosts_ip
    - samba_server
    - systemd_resolved
    - krb5_config
    - samba_config
    - samba_ad_dc_primary
