---
- hosts: samba
  name: Samba Primary DC
  roles:
    - update
    - cli/utils
    - hosts_ip
    - samba/server
    - systemd_resolved
    - krb5_config
    - samba/config
    - samba/ad_dc_primary
