---
artgdb_patroni:
  hosts:
    dba.arthomson.com:
      name: dba
      ip_address: 10.0.100.121
    dbb.arthomson.com:
      name: dbb
      ip_address: 10.0.100.122
    dbc.arthomson.com:
      name: dbc
      ip_address: 10.0.100.123
