---
pipdb_pgpool:
  vars:
    ansible_python_interpreter: "/usr/bin/python3"
    POSTGRES_VERSION: "14"
    home: "/home/sysadmin"
    config: "/home/sysadmin/.config"
    local: "/home/sysadmin/.local"
    user: "sysadmin"
    distro: "bullseye"
    DOMAIN: "preeper.org"
    PG_CLUSTER: "artg-pip"
    PG_DATADIR: "/db/pgdata"
    PG_PORT: 5432
    HOST_NET: 10.0.30.0
    HOST_CIDR: 24
  hosts:
    dba.preeper.org:
      name: dba
      ip_address: 10.0.30.61
    dbb.preeper.org:
      name: dbb
      ip_address: 10.0.30.62
    dbc.preeper.org:
      name: dbc
      ip_address: 10.0.30.63
